name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS1: ${{ secrets.AWS1 }}
      AWS2: ${{ secrets.AWS2 }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6.9.0
        with:      
          context: .
          file: ./container/Dockerfile
          push: true
          tags: unlux/transcoding:latest  
        
      - name: Verify Pushed Image
        run: docker pull unlux/transcoding:latest
